/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alfredstateinventory.userinterface;

/**
 *
 * @author brand
 */
public class PanelHelpCenterDefault extends javax.swing.JPanel {

    /**
     * Creates new form PanelHelpCenterDefault
     */
    public PanelHelpCenterDefault() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblHelpCenterUsage = new javax.swing.JTextArea();
        lblTitle = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 675), new java.awt.Dimension(20, 675), new java.awt.Dimension(20, 675));

        setLayout(new java.awt.GridBagLayout());

        lblHelpCenterUsage.setEditable(false);
        lblHelpCenterUsage.setBackground(java.awt.SystemColor.control);
        lblHelpCenterUsage.setColumns(20);
        lblHelpCenterUsage.setLineWrap(true);
        lblHelpCenterUsage.setRows(4);
        lblHelpCenterUsage.setText("To get help with a topic, use the combo box to select what you need help with. You can find helpful Navigation articles which helps you understand each part of the application and how to use the interface, or How To articles which provide step by step instructions for common tasks.");
        lblHelpCenterUsage.setWrapStyleWord(true);
        lblHelpCenterUsage.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        add(lblHelpCenterUsage, gridBagConstraints);

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitle.setText("Welcome to the Help Center");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 50);
        add(lblTitle, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        add(filler2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler2;
    private javax.swing.JTextArea lblHelpCenterUsage;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
