/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alfredstateinventory.userinterface;

import alfredstateinventory.java.*;
import java.time.format.DateTimeFormatter;
import java.time.LocalDate;
import alfredstateinventory.userinterface.*;
import java.time.LocalDate;
import alfredstateinventory.sql.*;
import java.sql.*;
import java.util.ArrayList;

/**
 *
 * @author BHAsus
 */
public class ViewItemEquipment extends javax.swing.JPanel {

    /**
     * Creates new form EquipmentViewItem
     */
    public ViewItemEquipment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblItemIdTitle = new javax.swing.JLabel();
        lblItemId = new javax.swing.JLabel();
        lblItemNameTitle = new javax.swing.JLabel();
        lblItemName = new javax.swing.JLabel();
        lblItemAvailable = new javax.swing.JLabel();
        btnAvailable = new javax.swing.JCheckBox();
        lblLastSeenTitle = new javax.swing.JLabel();
        lblLastSeen = new javax.swing.JLabel();
        lblLocationTitle = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        btnEdit = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        lblItemIdTitle.setText("Item ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        add(lblItemIdTitle, gridBagConstraints);

        lblItemId.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        lblItemId.setText("SRVR_EJ414");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        add(lblItemId, gridBagConstraints);

        lblItemNameTitle.setText("Item Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        add(lblItemNameTitle, gridBagConstraints);

        lblItemName.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        lblItemName.setText("Windows Server 2016");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        add(lblItemName, gridBagConstraints);

        lblItemAvailable.setText("Item Available");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        add(lblItemAvailable, gridBagConstraints);

        btnAvailable.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        btnAvailable.setSelected(true);
        btnAvailable.setText("Available");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 0);
        add(btnAvailable, gridBagConstraints);

        lblLastSeenTitle.setText("Last Seen");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        add(lblLastSeenTitle, gridBagConstraints);

        lblLastSeen.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        lblLastSeen.setText("12: 21, 3/19/19");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        add(lblLastSeen, gridBagConstraints);

        lblLocationTitle.setText("Location");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        add(lblLocationTitle, gridBagConstraints);

        lblLocation.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        lblLocation.setText("SET 441");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        add(lblLocation, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        add(filler1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 2;
        add(filler2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        add(filler3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        add(filler4, gridBagConstraints);

        btnEdit.setBackground(java.awt.SystemColor.control);
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alfredstateinventory/drawable/GearIcon.png"))); // NOI18N
        btnEdit.setBorder(null);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        add(btnEdit, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        AlfredStateInventory.switchLayout("PanelDetails", btnEdit.getActionCommand());
    }//GEN-LAST:event_btnEditActionPerformed
    /**
     * Description: Populates all fields in current inventory item view
     * @param inventoryItem
     */
    public void populateItemView(InventoryItem inventoryItem) {
        lblItemId.setText("" + inventoryItem.getID());
        btnEdit.setActionCommand("" + inventoryItem.getID());
        lblItemName.setText(inventoryItem.getItemName());
        btnAvailable.setSelected(inventoryItem.getItemAvailable());
        lblLastSeen.setText(inventoryItem.getLastSeen().format(DateTimeFormatter.ofPattern("MM/dd/yyyy")));
        lblLocation.setText(inventoryItem.getLocation());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox btnAvailable;
    private javax.swing.JButton btnEdit;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JLabel lblItemAvailable;
    private javax.swing.JLabel lblItemId;
    private javax.swing.JLabel lblItemIdTitle;
    private javax.swing.JLabel lblItemName;
    private javax.swing.JLabel lblItemNameTitle;
    private javax.swing.JLabel lblLastSeen;
    private javax.swing.JLabel lblLastSeenTitle;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblLocationTitle;
    // End of variables declaration//GEN-END:variables
}
